### ISSUE TITLE
Typescript errors after removing transform

### ISSUE THREAD

**Issue by jljorgenson18** [react-spring/react-use-gesture#95]
We are seeing the following the type errors when upgrading to 6.0.3 because transform was removed.

```
node_modules/react-use-gesture/dist/hooks.d.ts:19:100 - error TS2344: Type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "domTarget" | "event" | "pointerEvents" | "transform"' does not satisfy the constraint '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.
  Type '"transform"' is not assignable to type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.

19 export declare const useDrag: (handler: Handler<Coordinates>, config?: Partial<Pick<GestureConfig, "domTarget" | "event" | "window" | "pointerEvents" | "transform" | "enabled" | "drag" | "pinch" | "scroll" | "wheel" | "hover" | "move">> | undefined) => (...args: any[]) => ReactEventHandlers;
                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-use-gesture/dist/hooks.d.ts:20:100 - error TS2344: Type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "domTarget" | "event" | "pointerEvents" | "transform"' does not satisfy the constraint '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.
  Type '"transform"' is not assignable to type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.

20 export declare const useMove: (handler: Handler<Coordinates>, config?: Partial<Pick<GestureConfig, "domTarget" | "event" | "window" | "pointerEvents" | "transform" | "enabled" | "drag" | "pinch" | "scroll" | "wheel" | "hover" | "move">> | undefined) => (...args: any[]) => ReactEventHandlers;
                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-use-gesture/dist/hooks.d.ts:21:101 - error TS2344: Type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "domTarget" | "event" | "pointerEvents" | "transform"' does not satisfy the constraint '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.
  Type '"transform"' is not assignable to type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.

21 export declare const useHover: (handler: Handler<Coordinates>, config?: Partial<Pick<GestureConfig, "domTarget" | "event" | "window" | "pointerEvents" | "transform" | "enabled" | "drag" | "pinch" | "scroll" | "wheel" | "hover" | "move">> | undefined) => (...args: any[]) => ReactEventHandlers;
                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-use-gesture/dist/hooks.d.ts:22:102 - error TS2344: Type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "domTarget" | "event" | "pointerEvents" | "transform"' does not satisfy the constraint '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.
  Type '"transform"' is not assignable to type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.

22 export declare const useScroll: (handler: Handler<Coordinates>, config?: Partial<Pick<GestureConfig, "domTarget" | "event" | "window" | "pointerEvents" | "transform" | "enabled" | "drag" | "pinch" | "scroll" | "wheel" | "hover" | "move">> | undefined) => (...args: any[]) => ReactEventHandlers;
                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-use-gesture/dist/hooks.d.ts:23:101 - error TS2344: Type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "domTarget" | "event" | "pointerEvents" | "transform"' does not satisfy the constraint '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.
  Type '"transform"' is not assignable to type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.

23 export declare const useWheel: (handler: Handler<Coordinates>, config?: Partial<Pick<GestureConfig, "domTarget" | "event" | "window" | "pointerEvents" | "transform" | "enabled" | "drag" | "pinch" | "scroll" | "wheel" | "hover" | "move">> | undefined) => (...args: any[]) => ReactEventHandlers;
                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-use-gesture/dist/hooks.d.ts:24:103 - error TS2344: Type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "domTarget" | "event" | "pointerEvents" | "transform"' does not satisfy the constraint '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.
  Type '"transform"' is not assignable to type '"window" | "enabled" | "drag" | "scroll" | "wheel" | "move" | "pinch" | "hover" | "passiveEvents" | "domTarget" | "event" | "pointerEvents"'.

24 export declare const usePinch: (handler: Handler<DistanceAngle>, config?: Partial<Pick<GestureConfig, "domTarget" | "event" | "window" | "pointerEvents" | "transform" | "enabled" | "drag" | "pinch" | "scroll" | "wheel" | "hover" | "move">> | undefined) => (...args: any[]) => ReactEventHandlers;
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems like we just need to remove transform from hooks.d.ts.

**Comment by dbismut** [comment]
Reaaaallly sorry @jljorgenson18 this should be fixed in v6.0.6

**Comment by jljorgenson18** [comment]
No worries @dbismut
